version: '3.8'

services:
  ui:
    image: ghcr.io/astrophotograph/alp-experimental-ui:latest
    container_name: alp-ui
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped
    network_mode: host

  server:
    image: ghcr.io/astrophotograph/alp-experimental-server:latest
    container_name: alp-server
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    network_mode: host

  redis:
    image: redis:7-alpine
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
