version: '3.8'

services:
  ui:
    image: ghcr.io/astrophotograph/alp-experimental-ui:latest
    container_name: alp-ui
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - server
    restart: unless-stopped
    network_mode: host

  server:
    image: ghcr.io/astrophotograph/alp-experimental-server:latest
    container_name: alp-server
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - telescope-data:/app/data
    restart: unless-stopped
    network_mode: host

  redis:
    image: redis:7-alpine
    container_name: alp-redis
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local
  telescope-data:
    driver: local
